= Aurora Spring Boot Starter
:toc:
:toc-placement: preamble

A starter for including common configuration in Spring Boot for running an application on Aurora OpenShift. The starter
is part of the Aurora Reference Architecture and an example can be found at in the repository for
https://github.com/Skatteetaten/openshift-reference-springboot-server[the reference application].

The starter will add some of the standard Spring Boot starters;
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready[Spring Boot Actuator],
http://projects.spring.io/spring-hateoas/[Spring HATEOAS],
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools[Spring Boot Developer Tools]
and https://docs.spring.io/spring-boot/docs/2.0.x/reference/htmlsingle/#production-ready-metrics[Micrometer Prometheus]
in addition to pulling in the proprietary
https://github.com/Skatteetaten/aurora-header-mdc-filter[aurora-header-mdc-filter]. Please reference the documentation
for these individual components for details.

In addition to adding the mentioned dependencies, the starter also provides a couple of utilities on its own, descripted
next.

== How to use

[source,java]
----
package no.skatteetaten...;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import no.skatteetaten.aurora.annotations.AuroraApplication;

@SpringBootApplication
@AuroraApplication
public class Main {

    public static void main(String[] args) throws Exception {
        SpringApplication.run(Main.class, args);
    }
}
----

== Features

=== Register the Aurora Header MDC Filter

The starter will register the Aurora Header MDC Filter. The registration can be disabled with the property

  aurora.starter.headerfilter.enabled = false


=== Create property sources for Aurora config files

During startup a PropertySource for the configuration in the Aurora Secret properties file (auroraConfig[secret]) and
the Aurora Env properties file (auroraConfig[env]) will be created. These properties files are automatically mounted
when deploying on OpenShift based on your AuroraConfig. It will also create a property source from the environment
variables set by by the platform during deploy.


=== Graceful Shutdown Handler for Tomcat

The starter will add a graceful shutdown handler for Tomcat (without it Tomcat may terminate ongoing requests on SIGTERM)


=== The Aurora Management Interface

==== Default config values
info.serviceLinks.metrics={metricsHostname}/dashboard/db/openshift-project-spring-actuator-view?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}
info.podLinks.metrics={metricsHostname}/dashboard/db/openshift-project-spring-actuator-view-instance?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}&var-instance={podName}

management.health.status.order=DOWN, OUT_OF_SERVICE, UNKNOWN, OBSERVE, UP


=== Metrics


=== Auto registration of DataSource


=== Configuration of the Actuator Endpoints

Most actuator endpoints will be disabled by default;

* auditevents
* heapdump
* metrics
* logfile
* autoconfig
* configprops
* mappings
* beans
* dump
* jolokia

Actuator will also be configured to use the port specified by the `MANAGEMENT_HTTP_PORT` environment variable. The
value of this variable will be set by the Aurora platform when deploying. Security on the actuator endpoints and the
metrics filter will be disabled.


=== Setting of Spring Boot Properties
spring.application.name=${APP_NAME:my}-${POD_NAMESPACE:app}
spring.jackson.date-format=com.fasterxml.jackson.databind.util.ISO8601DateFormat
flyway.out-of-order=true


