= Aurora Spring Boot Starter
:toc:
:toc-placement: preamble

A starter for including common configuration in Spring Boot for running an application on Aurora OpenShift. The starter
is part of the Aurora Reference Architecture and an example can be found at in the repository for
https://github.com/Skatteetaten/openshift-reference-springboot-server[the reference application].

The starter will add some of the standard Spring Boot starters;
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready[Spring Boot Actuator],
http://projects.spring.io/spring-hateoas/[Spring HATEOAS],
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools[Spring Boot Developer Tools]
and https://docs.spring.io/spring-boot/docs/2.0.x/reference/htmlsingle/#production-ready-metrics[Micrometer Prometheus]
in addition to pulling in the proprietary
https://github.com/Skatteetaten/aurora-header-mdc-filter[aurora-header-mdc-filter]. Please reference the documentation
for these individual components for details.

In addition to adding the mentioned dependencies, the starter also provides a couple of utilities on its own, descripted
next.

== How to use
Include the starter as a dependency

[source,xml]
----
<dependency>
  <groupId>no.skatteetaten.aurora.springboot</groupId>
  <artifactId>aurora-spring-boot-starter</artifactId>
  <version>${aurora.starters.version}</version>
</dependency>
----

Adjust your maven start class to look like this


[source, java]
----
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;

import io.micrometer.spring.autoconfigure.export.StringToDurationConverter;

@SpringBootApplication
@Configuration
@Import(StringToDurationConverter.class)
public class Main {

    protected Main() {
    }

    public static void main(String[] args) throws Exception {
        SpringApplication.run(Main.class, args);
    }
}
----

Add the following to your application.yaml file
[source]
----
spring:
    metrics:
        prometheus:
            timerPercentilesMax: "PT5S"
            timerPercentilesMin: "PT0.1S"
----

There is a bug in micrometer 1.0.0-rc2 prometheus support that required the manual import of the StringToDurationConverter, this also prohibits us from setting default vaules for timerPercentils.
This will be fixed in an upcomming version of this starter.

== Features

=== Register the Aurora Header MDC Filter

The starter will register the Aurora Header MDC Filter. The registration can be disabled with the property

  aurora.starter.headerfilter.enabled = false


=== Create property sources for Aurora config files

During startup a PropertySource for the configuration in the Aurora Secret properties file (auroraConfig[secret]) and
the Aurora Env properties file (auroraConfig[env]) will be created. These properties files are automatically mounted
when deploying on OpenShift based on your AuroraConfig. It will also create a property source from the environment
variables set by by the platform during deploy.


=== Graceful Shutdown Handler for Tomcat

The starter will add a graceful shutdown handler for Tomcat (without it Tomcat may terminate ongoing requests on SIGTERM)


=== The Aurora Management Interface

The starter will help you implement the requirements for the Aurora Management Interface by setting some common
configuration values. For more information see
https://aurora/wiki/pages/viewpage.action?pageId=121279406[Management interface og helseovervåkning].

Note that the `management.port` will be set to the value of the `MANAGEMENT_HTTP_PORT` environment variable provided
by the platform. The default is to put all actuator endpoints on a different port than the main application/api
endpoints.

[source]
----
info.serviceLinks.metrics={metricsHostname}/dashboard/db/openshift-project-spring-actuator-view?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}

info.podLinks.metrics={metricsHostname}/dashboard/db/openshift-project-spring-actuator-view-instance?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}&var-instance={podName}

management.health.status.order=DOWN, OUT_OF_SERVICE, UNKNOWN, OBSERVE, UP
management.port=${MANAGEMENT_HTTP_PORT:8081}
----

=== Metrics

The starter will automatically add http://micrometer.io[Micrometer] (the upcoming spring boot default) as the default
metrics registry and also add `micrometer-registry-prometheus` for providing the `/prometheus` actuator endpoint that
will be (optionally) read by Prometheus automatically for all applications deployed on Aurora OpenShift.

Additionally a number of Micrometer metrics collectors will be automatically registered;

* JvmThreadMetrics
* ProcessorMetrics
* JvmGcMetrics
* JvmMemoryMetrics
* LogbackMetrics
* UptimeMetrics
* FileDescriptorMetrics

To get an overview of how Micrometer works we encourage you to read the Micrometer docs:
https://micrometer.io/docs/prometheus. Especially the Spring Support section (https://micrometer.io/docs/prometheus#_spring_support)
that will describe what is auto configured for you, and what you get out of the box in a Spring Boot application.

Outgoing and incomming HTTP metrics have timerPercentiles set by default.
[source]
----
spring.metrics.web.client.record-request-percentiles=true
spring.metrics.web.server.record-request-percentiles=true
----

=== Auto registration of DataSource

If a database is provided on OpenShift there will automatically be a DataSource created from the properties files provided
by the platform. If you want to override to use a specific database you can set the `aurora.db` property if you have more
than one db in your application.

Connection count metrics will also be collected from the DataSource.

=== Configuration of the Actuator Endpoints

Most actuator endpoints will be disabled by default;

* auditevents
* heapdump
* metrics
* logfile
* autoconfig
* configprops
* mappings
* beans
* dump
* jolokia

Actuator will also be configured to use the port specified by the `MANAGEMENT_HTTP_PORT` environment variable. The
value of this variable will be set by the Aurora platform when deploying. Security on the actuator endpoints and the
metrics filter will be disabled.


=== Setting of Spring Boot Properties

The spring boot application name will be set from the environment variables APP_NAME and POD_NAMESPACE provided by the
platform when deploying to Aurora OpenShift.

The `flyway.out-of-order` mode will also be activated to allow migrations to be developed in different feature branches
at the same time. See the Flyway documentation for more information.

The AURORA_VERSION and IMAGE_BUILD_TIME variables are included in spring boots actuator output since we use them in a central
management overview dashboard.

[source]
----
spring.application.name=${APP_NAME:my}-${POD_NAMESPACE:app}
spring.jackson.date-format=com.fasterxml.jackson.databind.util.ISO8601DateFormat
flyway.out-of-order=true
info.auroraVersion= ${AURORA_VERSION:local-dev}
info.imageBuildTime=${IMAGE_BUILD_TIME:}
----


